# Generated by Django 6.1 on 2026-09-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_product_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='food_style',
            field=models.CharField(choices=[('Indian', 'Indian'), ('Chinese', 'Chinese'), ('Italian', 'Italian'), ('Japanese', 'Japanese'), ('Mexican', 'Mexican'), ('French', 'French'), ('Western', 'Western'), ('Beverages & Desserts', 'Beverages & Desserts')], default='Indian', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='food_type',
            field=models.CharField(choices=[('Vegetarian', 'Vegetarian'), ('Non-Vegetarian', 'Non-Vegetarian')], default='Vegetarian', max_length=20),
        ),
    ]
