# Generated by Django 6.1 on 2026-09-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_product_food_style_product_food_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='menu_image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
